name: hawk
channels:
- conda-forge
- defaults
dependencies:
- pip
- python>=3.9,<3.11
- pywps>=4.5.2,<4.7
- jinja2
- click
- psutil
- birdy
#- tigramite
#- tefs==0.3.1
- pandas
- scikit-learn
- numpy
# tests
- pytest
